language: node_js

node_js:
        - 12

services:
        - docker

install:
	- echo "nothing to install"

before_script:
        - echo 'nothing'

script:
        - docker --version
        - docker-compose -f docker-compose-build.yaml build --parallel

after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --pasword-stdin
        - docker push feliciodeangela/udagram-frontend:local
        - docker push feliciodeangela/reverseproxy
        - docker push feliciodeangela/udagram-api-user
        - docker push feliciodeangela/udagram-api-feed